### ISSUE TITLE
Note for newcomers

### ISSUE THREAD

**Issue by kowyo** [ros-navigation/navigation2_tutorials#98]
This repo only has one branch and therefore code was updated for new ROS versions (like Rolling).

I am using ROS Humble and have already found some incompatible code as #96 has mentioned.

If maintainers notice this please create branches for different ROS versions.

If not, I suggest you use files from older commit, which should be more consistant with docs in nav2.

**Comment by SteveMacenski** [comment]
Working on this today, will support humble / jazzy / rolling in separate branches shortly. 

- [x] main -> rolling
- [x] jazzy
- [x] humble
